export const ARTICLE_REQUEST = 'ARTICLE_REQUEST';
export const ARTICLE_REQUEST_SUCCESS = 'ARTICLE_REQUEST_SUCCESS';
export const ARTICLE_REQUEST_FAILE = 'ARTICLE_REQUEST_FAILE';


export const ARTICLE_INITIAL_REQUEST = 'ARTICLE_INITIAL_REQUEST';
export const ARTICLE_INITIAL_REQUEST_SUCCESS = 'ARTICLE_INITIAL_REQUEST_SUCCESS';
export const ARTICLE_INITIAL_REQUEST_FAILE = 'ARTICLE_INITIAL_REQUEST_FAILE';



export const ARTICLE_SEARCH_REQUEST = 'ARTICLE_SEARCH_REQUEST';
export const ARTICLE_SEARCH_REQUEST_SUCCESS = 'ARTICLE_SEARCH_REQUEST_SUCCESS';
export const ARTICLE_SEARCH_REQUEST_FAILE = 'ARTICLE_SEARCH_REQUEST_FAILE';
export const CLEAR_STATE = 'CLEAR_STATE';